export const SET_TOKEN = 'SET_TOKEN' // 登录获取token信息
export const DELTOKEN = 'DELTOKEN' // 登出
export const REGISTER = 'REGISTER' // 注册
export const ACCREGISTER = 'ACCREGISTER' // 精准注册
export const TEMPLATEINFO = 'TEMPLATEINFO' // 下级模板
export const MEMREGISTER = 'MEMREGISTER' // 会员注册
export const ACCLINK = 'ACCLINK' // 创建链接 代理
export const MEMLINK = 'MEMLINK' // 创建链接 会员
export const MANALINK = 'MANALINK' // 链接管理
export const REMOVELINK = 'REMOVELINK' // 删除链接
export const QUERYINVITE = 'QUERYINVITE' // 查询代理链接
export const COMQUERYINVITE = 'QUERYINVITE' // 查询佣金设置所有下级
export const QUERYTEMPLATEINFO = 'QUERYTEMPLATEINFO' // 查询模板信息
export const UPDATETEMPINFO = 'UPDATETEMPINFO' // 批量更新模板
export const ADDINVITE = 'ADDINVITE' // 追加下级用户
export const FINDSINGLELINK = 'FINDSINGLELINK' // 查找单个链接
export const FINDPACKET = 'FINDPACKET' // 红包列表
export const ADDMANALINK = 'ADDMANALINK' // 添加链接管理
export const QUERYBYLEVEL = 'QUERYBYLEVEL' // 查找用户下级
export const ADDQUERYBYLEVEL = 'ADDQUERYBYLEVEL' // 追加用户下级
export const BACKTYPE = 'BACKTYPE'
